[package]
name = "adskalman-examples"
description = "Examples for the adskalman crate"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.27"
adskalman = {path=".."}
nalgebra-rand-mvn = {git="https://github.com/strawlab/nalgebra-rand-mvn", rev="e3a4528a08aeebce74036402bab42ebe47d4a56f"}
env_logger = "0.8"
log = { version = "0.4", features = ["release_max_level_debug"] }
anyhow = "1.0"
